import { useEffect, useState } from 'react'
import { Search, MapPin } from 'lucide-react'
import { useDispatch, useSelector } from 'react-redux'
import { fetchTrains, searchTrains } from '../features/trains/trainSlice'
import { ArrowLeft, Menu, UserRound, WalletCards, X } from 'lucide-react'
import { Link, useLocation, useNavigate, useSearchParams } from 'react-router-dom'
import useAuth from '../hooks/useAuth'

export default function TrainSearchPage() {
  const dispatch = useDispatch(); const [params] = useSearchParams()
  const { trains = [], loading = false, error = null } = useSelector(s => s?.trains || {})
  const safeTrains = Array.isArray(trains) ? trains : []
  const [query, setQuery] = useState('')
  useEffect(() => { dispatch(fetchTrains(Object.fromEntries(params.entries()))) }, [dispatch, params])
  const submit = e => { e.preventDefault(); query.trim() ? dispatch(searchTrains(query)) : dispatch(fetchTrains()) }
  return <Portal title="Train search" eyebrow="Passenger information"><form onSubmit={submit} className="mb-8 flex max-w-2xl gap-3"><input value={query} onChange={e => setQuery(e.target.value)} className="field" placeholder="Search by train number or name" /><button className="rounded-2xl bg-ink px-6 text-white"><Search size={19} /></button></form>{loading && <p className="text-slate-500">Loading trains...</p>}{error && <p className="text-flare">{error}</p>}<div className="grid gap-4">{safeTrains.map(train => <Link to={`/trains/${train._id}`} key={train._id} className="grid gap-5 rounded-3xl border border-ink/10 bg-white p-6 transition hover:-translate-y-1 hover:shadow-soft md:grid-cols-[1fr_1.4fr_1fr]"><div><p className="text-xs font-bold uppercase tracking-widest text-plum">{train.trainNumber}</p><h3 className="mt-2 text-lg font-bold">{train.trainName}</h3></div><div className="flex items-center gap-3 text-sm text-slate-500"><MapPin size={17} className="text-flare" />{train.source?.stationCode || 'Origin'} <span>→</span> {train.destination?.stationCode || 'Destination'}</div><div className="flex items-center justify-between md:block md:text-right"><p className={train.status === 'Delayed' ? 'font-bold text-flare' : 'font-bold text-emerald-600'}>{train.status}</p><p className="mt-1 text-sm text-slate-400">Platform {train.platformNumber || 'TBA'} · {train.scheduledDeparture || '--:--'}</p></div></Link>)}</div></Portal>
}

export function Portal({ title, eyebrow, children }) {
  const [scrolled, setScrolled] = useState(false); const [open, setOpen] = useState(false); const navigate = useNavigate(); const location = useLocation(); const { isAuthenticated, user } = useAuth()
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 12); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll) }, [])
  const links = [['Home', '/'], ['Find trains', '/trains'], ['Station board', '/station-board'], ['PNR status', '/pnr'], ['Bookings', '/bookings'], ['Food', '/food']]
  return <div className="min-h-screen bg-mist text-ink"><header className={`sticky top-0 z-40 transition-all duration-300 ${scrolled ? 'mx-3 mt-3 rounded-[1.4rem] border border-white/20 bg-plum-950/90 shadow-xl backdrop-blur-xl lg:mx-8' : 'border-b border-ink/10 bg-white/90 backdrop-blur-md'}`}><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link to="/" className="flex items-center gap-3 text-ink"><img src="/logo.svg" className="h-10 w-10" alt="Rail Center" /><span className={`font-display text-xl ${scrolled ? 'text-white' : ''}`}>RC Rail Center</span></Link><nav className={`hidden items-center gap-5 text-sm font-semibold md:flex ${scrolled ? 'text-white/75' : 'text-text-secondary'}`}>{links.map(([label, href]) => <Link key={href} to={href} className="transition hover:text-lilac">{label}</Link>)}</nav><div className="hidden items-center gap-2 md:flex">{isAuthenticated ? <><Link to="/wallet" className={`rounded-full border px-3 py-2 text-sm font-bold ${scrolled ? 'border-white/20 text-white' : 'border-plum/15 text-plum'}`}><WalletCards className="mr-1 inline" size={15} />Wallet</Link><Link to="/profile" className={`rounded-full p-2 ${scrolled ? 'text-white' : 'text-plum'}`} title={user?.name || 'Profile'}><UserRound size={18} /></Link></> : <Link to="/login" className="rounded-full bg-plum-950 px-4 py-2 text-sm font-bold text-white">Login</Link>}</div><button className={`md:hidden ${scrolled ? 'text-white' : 'text-ink'}`} onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X size={21} /> : <Menu size={21} />}</button></div>{open && <div className="grid gap-3 border-t border-white/10 px-5 py-4 text-sm font-semibold text-white md:hidden">{links.map(([label, href]) => <Link onClick={() => setOpen(false)} key={href} to={href}>{label}</Link>)}</div>}</header><main className="mx-auto max-w-7xl px-6 py-10 lg:px-10"><button onClick={() => location.key !== 'default' ? navigate(-1) : navigate('/')} className="mb-7 inline-flex items-center gap-2 rounded-full border border-plum/15 bg-white px-4 py-2 text-sm font-bold text-plum transition hover:bg-lavender-50"><ArrowLeft size={16} /> Back</button><p className="text-xs font-bold uppercase tracking-[.2em] text-flare">{eyebrow}</p><h1 className="mt-3 mb-10 font-display text-5xl">{title}</h1>{children}</main></div>
}
