const User = require('../models/User');
const WalletTransaction = require('../models/WalletTransaction');
const { success, failure } = require('../utils/apiResponse');
const apply = async ({ userId, type, amount, reason, referenceType, referenceId, createdBy }) => {
  const numericAmount = Number(amount);
  if (!Number.isFinite(numericAmount) || numericAmount <= 0) { const error = new Error('A positive wallet amount is required'); error.statusCode = 400; throw error; }
  const signed = type === 'Debit' ? -numericAmount : numericAmount;
  const filter = type === 'Debit' ? { _id: userId, walletBalance: { $gte: numericAmount } } : { _id: userId };
  const user = await User.findOneAndUpdate(filter, { $inc: { walletBalance: signed } }, { new: true });
  if (!user) { const error = new Error(type === 'Debit' ? 'Insufficient demo wallet balance' : 'User not found'); error.statusCode = type === 'Debit' ? 400 : 404; throw error; }
  return WalletTransaction.create({ user: userId, type, amount: numericAmount, reason, referenceType, referenceId, createdBy, balanceAfterTransaction: user.walletBalance });
};
exports.mine = async (req, res, next) => { try { const user = await User.findById(req.user._id).select('walletBalance walletCurrency'); const transactions = await WalletTransaction.find({ user: req.user._id }).sort({ createdAt: -1 }).limit(100); success(res, { user, transactions }); } catch (e) { next(e); } };
exports.addMoney = async (req, res, next) => { try { const amount = Number(req.body.amount); if (!amount || amount < 1 || amount > 50000) return failure(res, 'Choose a demo amount between ₹1 and ₹50,000', [], 400); await apply({ userId: req.user._id, type: 'Credit', amount, reason: 'Mock wallet top-up', referenceType: 'AdminAdjustment', createdBy: req.user._id }); const user = await User.findById(req.user._id).select('walletBalance walletCurrency'); req.app.get('io').emit('walletUpdated', { userId: req.user._id, walletBalance: user.walletBalance }); success(res, user, 'Demo money added'); } catch (e) { next(e); } };
exports.withdraw = async (req, res, next) => { try { const amount = Number(req.body.amount); if (!amount || amount < 1 || amount > 50000) return failure(res, 'Choose a withdrawal between ₹1 and ₹50,000', [], 400); await apply({ userId: req.user._id, type: 'Debit', amount, reason: 'Mock wallet withdrawal to source account', referenceType: 'Withdrawal', createdBy: req.user._id }); const user = await User.findById(req.user._id).select('walletBalance walletCurrency'); req.app.get('io').emit('walletUpdated', { userId: req.user._id, walletBalance: user.walletBalance }); success(res, user, 'Demo withdrawal recorded to source account'); } catch (e) { next(e); } };
exports.applyPromo = async (req, res, next) => { try { if (String(req.body.code || '').trim().toLowerCase() !== 'rupali15') return failure(res, 'Wrong promo code', [], 400); const alreadyUsed = await WalletTransaction.exists({ user: req.user._id, referenceType: 'PromoCode', reason: 'Promo code rupali15' }); if (alreadyUsed) return failure(res, 'This promo code has already been used', [], 409); await apply({ userId: req.user._id, type: 'Credit', amount: 150, reason: 'Promo code rupali15', referenceType: 'PromoCode', createdBy: req.user._id }); const user = await User.findById(req.user._id).select('walletBalance walletCurrency'); req.app.get('io').emit('walletUpdated', { userId: req.user._id, walletBalance: user.walletBalance }); success(res, user, '₹150 demo promo credit added'); } catch (e) { next(e); } };
exports.adminAdjust = async (req, res, next) => { try { const amount = Number(req.body.amount); const type = req.body.type === 'Debit' ? 'Debit' : 'Credit'; if (!amount || amount < 1) return failure(res, 'A positive amount is required', [], 400); await apply({ userId: req.params.id, type, amount, reason: req.body.reason || 'Admin wallet adjustment', referenceType: 'AdminAdjustment', createdBy: req.user._id }); success(res, await User.findById(req.params.id).select('name email walletBalance'), 'Wallet adjusted'); } catch (e) { next(e); } };
exports.adminTransactions = async (req, res, next) => { try { success(res, await WalletTransaction.find(req.query.user ? { user: req.query.user } : {}).populate('user createdBy', 'name email').sort({ createdAt: -1 })); } catch (e) { next(e); } };
exports.apply = apply;
