require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const User = require('../models/User'); const Station = require('../models/Station'); const Train = require('../models/Train'); const Announcement = require('../models/Announcement'); const EmployeeTask = require('../models/EmployeeTask'); const Booking = require('../models/Booking'); const FoodVendor = require('../models/FoodVendor'); const FoodOrder = require('../models/FoodOrder'); const WalletTransaction = require('../models/WalletTransaction');

const run = async () => {
  await connectDB();
  await Promise.all([User.deleteMany(), Station.deleteMany(), Train.deleteMany(), Announcement.deleteMany(), EmployeeTask.deleteMany(), Booking.deleteMany(), FoodVendor.deleteMany(), FoodOrder.deleteMany(), WalletTransaction.deleteMany()]);
  const stationData = [['New Delhi Railway Station', 'NDLS', 'New Delhi', 16], ['Mumbai Central', 'MMCT', 'Mumbai', 5], ['Howrah Junction', 'HWH', 'Kolkata', 23], ['Chennai Central', 'MAS', 'Chennai', 12], ['Bengaluru City Junction', 'SBC', 'Bengaluru', 10], ['Lucknow Charbagh', 'LKO', 'Lucknow', 9], ['Ahmedabad Junction', 'ADI', 'Ahmedabad', 12], ['Pune Junction', 'PUNE', 'Pune', 6], ['Nagpur Junction', 'NGP', 'Nagpur', 8], ['Hyderabad Deccan', 'HYB', 'Hyderabad', 6], ['Secunderabad Junction', 'SC', 'Secunderabad', 10], ['Jaipur Junction', 'JP', 'Jaipur', 6], ['Kota Junction', 'KOTA', 'Kota', 5], ['Bhopal Junction', 'BPL', 'Bhopal', 6], ['Indore Junction', 'INDB', 'Indore', 6], ['Patna Junction', 'PNBE', 'Patna', 10], ['Varanasi Junction', 'BSB', 'Varanasi', 9], ['Prayagraj Junction', 'PRYJ', 'Prayagraj', 10], ['Kanpur Central', 'CNB', 'Kanpur', 10], ['Agra Cantt', 'AGC', 'Agra', 6], ['Amritsar Junction', 'ASR', 'Amritsar', 7], ['Chandigarh', 'CDG', 'Chandigarh', 6], ['Dehradun', 'DDN', 'Dehradun', 4], ['Jammu Tawi', 'JAT', 'Jammu', 5], ['Srinagar', 'SINA', 'Srinagar', 3], ['Goa Madgaon', 'MAO', 'Madgaon', 5], ['Vasco da Gama', 'VSG', 'Vasco da Gama', 3], ['Bhubaneswar', 'BBS', 'Bhubaneswar', 6], ['Visakhapatnam', 'VSKP', 'Visakhapatnam', 8], ['Vijayawada Junction', 'BZA', 'Vijayawada', 10], ['Coimbatore Junction', 'CBE', 'Coimbatore', 6], ['Madurai Junction', 'MDU', 'Madurai', 8], ['Thiruvananthapuram Central', 'TVC', 'Thiruvananthapuram', 5], ['Kochi Ernakulam', 'ERS', 'Kochi', 6], ['Mysuru Junction', 'MYS', 'Mysuru', 5], ['Jodhpur Junction', 'JU', 'Jodhpur', 5], ['Udaipur City', 'UDZ', 'Udaipur', 3], ['Ranchi', 'RNC', 'Ranchi', 5], ['Guwahati', 'GHY', 'Guwahati', 7], ['Siliguri Junction', 'SGUJ', 'Siliguri', 5], ['Raipur Junction', 'R', 'Raipur', 6], ['Bilaspur Junction', 'BSP', 'Bilaspur', 5], ['Gwalior Junction', 'GWL', 'Gwalior', 5], ['Mangalore Central', 'MAQ', 'Mangaluru', 4], ['Tiruchirappalli Junction', 'TPJ', 'Tiruchirappalli', 5]];
  const stations = await Station.insertMany(stationData.map(([name, stationCode, city, totalPlatforms]) => ({ name, stationCode, city, totalPlatforms, platforms: Array.from({ length: totalPlatforms }, (_, i) => String(i + 1)) })));
  const byCode = Object.fromEntries(stations.map(station => [station.stationCode, station]));
  const route = (codes) => codes.map((code, index) => ({ station: byCode[code]._id, arrivalTime: `${String(6 + index * 2).padStart(2, '0')}:10`, departureTime: `${String(6 + index * 2).padStart(2, '0')}:20`, platformNumber: String((index % 6) + 1) }));
  const classes = codes => codes.map(([code, name, fare]) => ({ code, name, baseFare: fare, totalSeats: 72, availableSeats: 72 }));
  const trains = await Train.insertMany([
    { trainNumber: '12301', trainName: 'Rajdhani Express', category: 'Rajdhani', source: byCode.NDLS._id, destination: byCode.HWH._id, routeStops: route(['NDLS', 'LKO', 'HWH']), totalDurationMinutes: 1050, scheduledDeparture: '16:55', scheduledArrival: '10:00', platformNumber: '7', status: 'Delayed', delayMinutes: 12, delayReason: 'Weather conditions', classesAvailable: ['1A', '2A', '3A'], availableClasses: classes([['1A', 'First AC', 4200], ['2A', 'AC 2 Tier', 2600], ['3A', 'AC 3 Tier', 1850]]) },
    { trainNumber: '12002', trainName: 'Shatabdi Express', category: 'Shatabdi', source: byCode.NDLS._id, destination: byCode.LKO._id, routeStops: route(['NDLS', 'LKO']), totalDurationMinutes: 385, scheduledDeparture: '06:15', scheduledArrival: '12:40', platformNumber: '4', classesAvailable: ['CC', 'EC'], availableClasses: classes([['CC', 'Chair Car', 950], ['1A', 'Executive Chair Car', 1750]]) },
    { trainNumber: '22439', trainName: 'Vande Bharat Express', category: 'Vande Bharat', source: byCode.NDLS._id, destination: byCode.LKO._id, routeStops: route(['NDLS', 'LKO']), totalDurationMinutes: 265, scheduledDeparture: '06:00', scheduledArrival: '10:25', platformNumber: '3', classesAvailable: ['CC', 'EC'], availableClasses: classes([['CC', 'Chair Car', 1250], ['1A', 'Executive Chair Car', 2350]]) },
    { trainNumber: '12213', trainName: 'Duronto Express', category: 'Duronto', source: byCode.MMCT._id, destination: byCode.NDLS._id, routeStops: route(['MMCT', 'ADI', 'NDLS']), totalDurationMinutes: 990, scheduledDeparture: '23:00', scheduledArrival: '15:30', platformNumber: '2', classesAvailable: ['1A', '2A', '3A'], availableClasses: classes([['1A', 'First AC', 3900], ['2A', 'AC 2 Tier', 2400], ['3A', 'AC 3 Tier', 1700]]) },
    { trainNumber: '22405', trainName: 'Garib Rath Express', category: 'Express', source: byCode.NDLS._id, destination: byCode.MMCT._id, routeStops: route(['NDLS', 'ADI', 'MMCT']), totalDurationMinutes: 730, scheduledDeparture: '07:40', scheduledArrival: '19:50', platformNumber: '2', status: 'Delayed', delayMinutes: 18, delayReason: 'Signal maintenance', classesAvailable: ['3A'], availableClasses: classes([['3A', 'AC 3 Tier', 1150]]) },
  ]);
  const admin = await User.create({ name: 'System Admin', email: 'admin@railway.com', password: 'Admin@123', role: 'admin' });
  const employee = await User.create({ name: 'Station Employee', email: 'employee@railway.com', password: 'Employee@123', role: 'employee', assignedStation: byCode.NDLS._id });
  const passenger = await User.create({ name: 'Demo Passenger', email: 'passenger@railway.com', password: 'Passenger@123', role: 'passenger', favourites: [trains[0]._id], savedPassengers: [{ fullName: 'Demo Passenger', age: 21, gender: 'Other', berthPreference: 'No Preference' }] });
  const passengers = await Promise.all(Array.from({ length: 5 }, (_, index) => User.create({ name: `Demo Passenger ${index + 2}`, email: `passenger${index + 2}@railway.com`, password: 'Passenger@123', role: 'passenger' })));
  await Announcement.insertMany([
    { title: 'Platform change', message: 'Rajdhani Express will depart from platform 7 today.', station: byCode.NDLS._id, train: trains[0]._id, priority: 'high', createdBy: admin._id },
    { title: 'Welcome to Rail Center', message: 'Passenger information is refreshed throughout the day.', station: byCode.NDLS._id, priority: 'low', createdBy: employee._id },
    { title: 'Delay alert', message: 'Garib Rath Express is running 18 minutes late.', station: byCode.NDLS._id, train: trains[4]._id, priority: 'high', createdBy: admin._id },
    { title: 'Keep platforms clear', message: 'Please follow staff instructions while boarding.', station: byCode.MMCT._id, priority: 'medium', createdBy: admin._id },
    { title: 'Digital board maintenance', message: 'Some display boards may refresh briefly at 14:00.', station: byCode.LKO._id, priority: 'low', createdBy: employee._id },
  ]);
  await EmployeeTask.insertMany([
    { employee: employee._id, station: byCode.NDLS._id, title: 'Verify platform display', description: 'Confirm departure boards match the latest schedule.', dueDate: new Date(Date.now() + 86400000) },
    { employee: employee._id, station: byCode.NDLS._id, title: 'Inspect platform signage', description: 'Check signs on platforms 1 to 4.', dueDate: new Date(Date.now() + 86400000 * 2) },
    { employee: employee._id, station: byCode.NDLS._id, title: 'Review delay notices', description: 'Make sure delay reasons are visible to passengers.', status: 'In Progress', dueDate: new Date(Date.now() + 86400000) },
    { employee: employee._id, station: byCode.NDLS._id, title: 'Test announcement system', description: 'Run the afternoon public-address test.', dueDate: new Date(Date.now() + 86400000 * 3) },
    { employee: employee._id, station: byCode.NDLS._id, title: 'Complete shift handover', description: 'Record outstanding station operations before handover.', status: 'Completed', dueDate: new Date() },
  ]);
  const bookings = await Booking.insertMany([
    { bookingReference: 'RMS-2026-DEMO01', pnrNumber: '2600000001', passenger: passenger._id, train: trains[2]._id, journeyDate: new Date(Date.now() + 86400000 * 3), boardingStation: byCode.NDLS._id, destinationStation: byCode.LKO._id, travelClass: 'CC', passengerCount: 2, totalFare: 2500, paymentMethod: 'Mock Wallet', paymentStatus: 'Paid', bookingStatus: 'Confirmed' },
    { bookingReference: 'RMS-2026-DEMO02', pnrNumber: '2600000002', passenger: passenger._id, train: trains[0]._id, journeyDate: new Date(Date.now() + 86400000 * 5), boardingStation: byCode.NDLS._id, destinationStation: byCode.HWH._id, travelClass: '2A', passengerCount: 1, totalFare: 2600, paymentMethod: 'Demo UPI', paymentStatus: 'Paid', bookingStatus: 'Confirmed' },
    { bookingReference: 'RMS-2026-DEMO03', pnrNumber: '2600000003', passenger: passenger._id, train: trains[4]._id, journeyDate: new Date(Date.now() + 86400000 * 7), boardingStation: byCode.NDLS._id, destinationStation: byCode.MMCT._id, travelClass: '3A', passengerCount: 3, totalFare: 3450, paymentMethod: 'Mock Wallet', paymentStatus: 'Paid', bookingStatus: 'Confirmed' },
  ]);
  const vendors = await FoodVendor.insertMany([
    { name: 'Platform Tiffin Co.', station: byCode.NDLS._id, cuisineTypes: ['North Indian', 'Snacks'], rating: 4.5, menu: [{ itemName: 'Paneer Thali', description: 'Complete vegetarian meal', category: 'North Indian', isVeg: true, price: 220 }, { itemName: 'Masala Chai', category: 'Beverages', isVeg: true, price: 45 }] },
    { name: 'Southern Express Kitchen', station: byCode.MMCT._id, cuisineTypes: ['South Indian'], rating: 4.2, menu: [{ itemName: 'Idli Sambar', category: 'South Indian', isVeg: true, price: 120 }, { itemName: 'Lemon Rice', category: 'South Indian', isVeg: true, price: 140 }] },
    { name: 'Junction Bites', station: byCode.LKO._id, cuisineTypes: ['Chinese', 'Beverages'], rating: 4.1, menu: [{ itemName: 'Veg Noodles', category: 'Chinese', isVeg: true, price: 180 }, { itemName: 'Fresh Juice', category: 'Beverages', isVeg: true, price: 90 }] },
  ]);
  await FoodOrder.insertMany(Array.from({ length: 5 }, (_, index) => ({ orderReference: `FOOD-2026-DEMO${index + 1}`, passenger, booking: bookings[index % bookings.length], train: trains[index % trains.length], vendor: vendors[index % vendors.length], deliveryStation: stations[index % stations.length], coachNumber: 'C1', seatNumber: String(21 + index), items: [{ itemName: 'Paneer Thali', quantity: 1, unitPrice: 220 }], totalAmount: 220, paymentMethod: 'Mock Wallet', paymentStatus: 'Paid', orderStatus: ['Placed', 'Preparing', 'Dispatched', 'Delivered', 'Placed'][index] })));
  await WalletTransaction.insertMany(Array.from({ length: 10 }, (_, index) => ({ user: index % 2 ? passengers[index % passengers.length]._id : passenger._id, type: index % 3 === 0 ? 'Credit' : 'Debit', amount: 100 + index * 25, reason: 'Seed demo transaction', referenceType: index % 2 ? 'Booking' : 'AdminAdjustment', balanceAfterTransaction: 0, createdBy: admin._id })));
  console.log('Seed data inserted successfully');
  await mongoose.connection.close();
};
run().catch(async error => { console.error(error); await mongoose.connection.close(); process.exit(1); });
